version: "3"

services:
  application:
    image: webdevops/php-nginx:7.3-alpine
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    ports:
      - 80:80
    volumes:
    - ./:/app