version: "3"

services:
  application:
    image: webdevops/php-nginx:7.3-alpine
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    ports:
      - 80:80
    volumes:
    - ./code:/app

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: ')mS-hu>`eWfrH8K'
      MYSQL_ROOT_PASSWORD: ')mS-hu>`eWfrH8K'
    ports:
      - 3306:3306
    volumes:
      - blog:/var/lib/mysql

volumes:
  blog: